version: '3'
services:
  app:
    restart: on-failure #unless-stopped
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=${URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_completed_successfully #change
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
